pool:
  vmImage: ubuntu-latest
 
steps:
 
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
 
# - bash: npm install uuid
 
- task: JavaToolInstaller@0
  displayName: 'Use Java 11'
  inputs:
    versionSpec: 11
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'bstack-conn'
    browserstackLocal: true
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'App Automate'
  
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sqGradlePluginVersionChoice: 'specify'
